### ISSUE TITLE
Investigate if there is an existing TS WIT binding generator available

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem#408]
In (closed) issues of `wit-bindgen` there are traces of some existing `.d.ts` code generation. But we are using `componentize-js` and `jco` not `wit-bindgen` directly. This task is to try to find if there is any existing (even if in-progress or broken) implementation of generating typed typescript bindings from WIT, and if possible, document how to use it with Golem.

**Comment by jdegoes** [comment]
It looks like they don't want Typescript support in `wit-bindgen` due to overlap with JS support:

https://github.com/bytecodealliance/wit-bindgen/issues/144

In a quick search, this is the closest thing I found:

https://github.com/tauri-apps/tauri-bindgen

I wonder if, rather than generating Typescript bindings, we should instead figure out what a code-first approach looks like in Typescript, and then build  that, leveraging the existing Javascript bindings? Assuming we can't find anything that does what we need out there.
